hooks:
  after:bump: yarn auto-changelog -p
  after:release:
    - 'docker build -t gcr.io/cramkle/cramkle-api:${version} .'
    - 'docker push gcr.io/cramkle/cramkle-api:${version}'
git:
  tagName: 'v${version}'
  tagAnnotation: 'Release v${version}'
  commitMessage: 'Release v${version}'
  changelog: yarn auto-changelog
